//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugOutNetLibrary.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ColumnName { get; set; }
        public bool SortDirection { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Created { get; set; }
    }
}
