USE [master]
GO

/****** Object:  Database [BugOutNet]    Script Date: 8/30/2016 3:45:13 PM ******/
CREATE DATABASE [BugOutNet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BugOutNet', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\BugOutNet.mdf' , SIZE = 6144KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BugOutNet_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\BugOutNet_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BugOutNet] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BugOutNet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BugOutNet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BugOutNet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BugOutNet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BugOutNet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BugOutNet] SET ARITHABORT OFF 
GO

ALTER DATABASE [BugOutNet] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BugOutNet] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [BugOutNet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BugOutNet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BugOutNet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BugOutNet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BugOutNet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BugOutNet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BugOutNet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BugOutNet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BugOutNet] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BugOutNet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BugOutNet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BugOutNet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BugOutNet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BugOutNet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BugOutNet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BugOutNet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BugOutNet] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BugOutNet] SET  MULTI_USER 
GO

ALTER DATABASE [BugOutNet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BugOutNet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BugOutNet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BugOutNet] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BugOutNet] SET  READ_WRITE 
GO

